language: groovy

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq git

install:
 - ./gradlew --stacktrace --debug assemble

jdk:
  - oraclejdk7

script: "./gradlew test --stacktrace --debug"